org.gradle.jvmargs=-Xmx1G

maven_group=io.github.izakyl
archives_base_name=folkways
mod_id=folkways
mod_version=0.1.0
minecraft_version=1.21.1
minecraft_requirement=[1.21.1,1.21.2)
neoforge_version=21.1.233
loader_version_range=[4,)
neoforge_requirement=[21.1.233,)
java_release=21

ponder_version=1.0.82+mc1.21.1
flywheel_version=1.0.6

starlark_version=4.2.1

ldlib_version=2.2.37
ldlib_requirement=[2.2.37,)
